# Generated by Django 2.2.5 on 2019-09-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
