# Generated by Django 2.2.5 on 2019-09-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_auto_20190918_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='download_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
