# Generated by Django 2.2.5 on 2019-09-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20190929_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='ip_list',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
