# Generated by Django 2.2.5 on 2019-09-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20190929_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='download_count',
            new_name='total_download',
        ),
        migrations.AddField(
            model_name='cv',
            name='unique_download',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='ip',
            field=models.ManyToManyField(blank=True, to='cv.IP'),
        ),
    ]
